version: "3"
services:
  needs_db:
    image: mysql:5.7
    ports:
      - 3307:3306
    tmpfs:
      - /var/lib/mysql
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp --sql_mode="NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES,ONLY_FULL_GROUP_BY,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ZERO_DATE,NO_ZERO_IN_DATE"
    environment:
      MYSQL_ROOT_PASSWORD: test
